<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>procedure-extract</AssemblyName>
    <RootNamespace>SfxProviders.ProcedureExtract</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\..\sfx-dal\SFX.DAL.csproj" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>

</Project>


